import type { MaintenanceData } from "./maintenance.types";

export const dummyMaintenanceData: MaintenanceData = {
  user: {
    name: "Employee",
    role: "Employee",
  },

  assets: [
    { id: "asset-1", assetTag: "AF-0114", name: "Laptop Dell XPS 13" },
    { id: "asset-2", assetTag: "AF-0067", name: "Canon EOS 200D" },
    { id: "asset-3", assetTag: "AF-0031", name: "HP LaserJet Pro" },
    { id: "asset-4", assetTag: "AF-0092", name: "iPhone 14" },
    { id: "asset-5", assetTag: "AF-0062", name: "Projector" },
    { id: "asset-6", assetTag: "AF-0003", name: "AC Unit" },
    { id: "asset-7", assetTag: "AF-0078", name: "Forklift" },
    { id: "asset-8", assetTag: "AF-0897", name: "Printer" },
    { id: "asset-9", assetTag: "AF-0873", name: "Office Chair" },
  ],

  technicians: [
    { id: "tech-1", name: "Ravi Varma" },
    { id: "tech-2", name: "Neha Patel" },
    { id: "tech-3", name: "Mitesh Jain" },
  ],

  requests: [
    {
      id: "maintenance-1",
      requestId: "MR-00023",
      assetId: "asset-1",
      assetTag: "AF-0114",
      assetName: "Laptop Dell XPS 13",
      issue: "Battery not charging",
      description: "Battery drains immediately after disconnecting the charger.",
      requestedBy: "Priya Sharma",
      requestedOn: "12 May 2025",
      priority: "HIGH",
      status: "PENDING",
    },
    {
      id: "maintenance-2",
      requestId: "MR-00022",
      assetId: "asset-2",
      assetTag: "AF-0067",
      assetName: "Canon EOS 200D",
      issue: "Lens not focusing",
      requestedBy: "Neha Patel",
      requestedOn: "10 May 2025",
      priority: "MEDIUM",
      status: "APPROVED",
      approvedBy: "Anita Desai",
    },
    {
      id: "maintenance-3",
      requestId: "MR-00021",
      assetId: "asset-3",
      assetTag: "AF-0031",
      assetName: "HP LaserJet Pro",
      issue: "Paper jam issue",
      requestedBy: "Mitesh Jain",
      requestedOn: "08 May 2025",
      priority: "MEDIUM",
      status: "TECHNICIAN_ASSIGNED",
      approvedBy: "Vikram Singh",
      technicianId: "tech-1",
      technicianName: "Ravi Varma",
    },
    {
      id: "maintenance-4",
      requestId: "MR-00020",
      assetId: "asset-4",
      assetTag: "AF-0092",
      assetName: "iPhone 14",
      issue: "Screen flickering",
      requestedBy: "Rahul Verma",
      requestedOn: "06 May 2025",
      priority: "HIGH",
      status: "IN_PROGRESS",
      approvedBy: "Rohit Mehta",
      technicianId: "tech-2",
      technicianName: "Neha Patel",
    },
    {
      id: "maintenance-5",
      requestId: "MR-00019",
      assetId: "asset-9",
      assetTag: "AF-0873",
      assetName: "Office Chair",
      issue: "Chair repair",
      requestedBy: "Sneha Iyer",
      requestedOn: "04 May 2025",
      priority: "LOW",
      status: "RESOLVED",
      approvedBy: "Anita Desai",
      technicianId: "tech-3",
      technicianName: "Mitesh Jain",
      resolvedOn: "07 May 2025",
    },
  ],
};
