import type { BookingData } from "./booking.types";

export const dummyBookingData: BookingData = {
  user: {
    name: "Department Head",
    role: "Department Head",
  },

  resources: [
    {
      id: "resource-room-a",
      name: "Meeting Room A",
      type: "ROOM",
      location: "3rd Floor - Admin",
      capacity: 12,
      colorTone: "mint",
    },
    {
      id: "resource-room-b2",
      name: "Conference Room B2",
      type: "ROOM",
      location: "2nd Floor - Operations",
      capacity: 20,
      colorTone: "sky",
    },
    {
      id: "resource-vehicle-1",
      name: "Toyota Innova",
      type: "VEHICLE",
      location: "Parking - A1",
      capacity: 7,
      colorTone: "cream",
    },
    {
      id: "resource-projector-1",
      name: "Projector AF-0062",
      type: "EQUIPMENT",
      location: "Equipment Store",
      colorTone: "sage",
    },
  ],

  bookings: [
    {
      id: "booking-1",
      resourceId: "resource-room-a",
      resourceName: "Meeting Room A",
      title: "Team Standup",
      bookedBy: "Rope Mehta",
      date: "2025-05-15",
      startTime: "09:00",
      endTime: "10:00",
      status: "UPCOMING",
    },
    {
      id: "booking-2",
      resourceId: "resource-room-a",
      resourceName: "Meeting Room A",
      title: "Product Review",
      bookedBy: "Anita Desai",
      date: "2025-05-15",
      startTime: "10:30",
      endTime: "12:00",
      status: "UPCOMING",
    },
    {
      id: "booking-3",
      resourceId: "resource-room-a",
      resourceName: "Meeting Room A",
      title: "Client Meeting",
      bookedBy: "Sneha Iyer",
      date: "2025-05-15",
      startTime: "14:00",
      endTime: "15:30",
      status: "UPCOMING",
    },
    {
      id: "booking-4",
      resourceId: "resource-room-a",
      resourceName: "Meeting Room A",
      title: "Marketing Sync",
      bookedBy: "Priya Sharma",
      date: "2025-05-15",
      startTime: "11:30",
      endTime: "13:00",
      status: "OVERLAPPING",
      notes: "Conflicts with Product Review.",
    },
    {
      id: "booking-5",
      resourceId: "resource-room-b2",
      resourceName: "Conference Room B2",
      title: "Procurement Team",
      bookedBy: "Karan Malhotra",
      date: "2025-07-07",
      startTime: "09:00",
      endTime: "10:00",
      status: "UPCOMING",
    },
  ],
};
