import type { OrganizationData } from "./organization.types";

/**
 * Temporary data for testing the Organization Setup screen.
 *
 * The page reads this through getOrganizationData(). When Prisma is connected,
 * replace the repository implementation instead of changing the UI components.
 */
export const dummyOrganizationData: OrganizationData = {
  user: {
    name: "Admin User",
    role: "Administrator",
  },

  departments: [
    {
      id: "dept-it",
      name: "Information Technology",
      code: "IT",
      description: "Technology infrastructure and application support.",
      managerId: "user-anita",
      managerName: "Anita Desai",
      status: "Active",
      employeeCount: 34,
      assetCount: 128,
    },
    {
      id: "dept-hr",
      name: "Human Resources",
      code: "HR",
      description: "Employee operations and organizational development.",
      managerId: "user-rohit",
      managerName: "Rohit Mehta",
      status: "Active",
      employeeCount: 18,
      assetCount: 42,
    },
    {
      id: "dept-fin",
      name: "Finance",
      code: "FIN",
      description: "Finance administration and operational reporting.",
      managerId: "user-karan",
      managerName: "Karan Malhotra",
      status: "Active",
      employeeCount: 21,
      assetCount: 51,
    },
    {
      id: "dept-ops",
      name: "Operations",
      code: "OPS",
      description: "Day-to-day operational coordination.",
      managerId: "user-sneha",
      managerName: "Sneha Iyer",
      status: "Active",
      employeeCount: 47,
      assetCount: 176,
    },
    {
      id: "dept-admin",
      name: "Admin",
      code: "ADM",
      description: "General administration.",
      managerId: "user-vikram",
      managerName: "Vikram Singh",
      status: "Inactive",
      employeeCount: 8,
      assetCount: 19,
    },
    {
      id: "dept-rd",
      name: "Research & Development",
      code: "RND",
      description: "Research, prototyping and product development.",
      parentDepartmentId: "dept-ops",
      parentDepartmentName: "Operations",
      managerId: "user-arjun",
      managerName: "Arjun Nair",
      status: "Active",
      employeeCount: 26,
      assetCount: 94,
    },
  ],

  categories: [
    {
      id: "cat-electronics",
      name: "Electronics",
      description: "Laptops, phones, cameras, displays and accessories.",
      icon: "💻",
      status: "Active",
      assetCount: 187,
    },
    {
      id: "cat-furniture",
      name: "Furniture",
      description: "Desks, chairs, cabinets and meeting-room furniture.",
      icon: "🪑",
      status: "Active",
      assetCount: 96,
    },
    {
      id: "cat-vehicles",
      name: "Vehicles",
      description: "Cars, vans and other organization vehicles.",
      icon: "🚙",
      status: "Active",
      assetCount: 22,
    },
    {
      id: "cat-networking",
      name: "Networking Equipment",
      description: "Routers, switches, access points and cabling equipment.",
      icon: "🌐",
      parentCategoryId: "cat-electronics",
      parentCategoryName: "Electronics",
      status: "Active",
      assetCount: 74,
    },
    {
      id: "cat-office",
      name: "Office Equipment",
      description: "Printers, scanners and shared office equipment.",
      icon: "🖨️",
      status: "Active",
      assetCount: 63,
    },
    {
      id: "cat-legacy",
      name: "Legacy Devices",
      description: "Older equipment retained for historical reference.",
      icon: "📦",
      parentCategoryId: "cat-electronics",
      parentCategoryName: "Electronics",
      status: "Inactive",
      assetCount: 11,
    },
  ],

  employees: [
    {
      id: "user-anita",
      name: "Anita Desai",
      email: "anita.desai@assetflow.test",
      employeeId: "EMP-0012",
      phone: "+91 98765 11012",
      departmentId: "dept-it",
      departmentName: "Information Technology",
      role: "MANAGER",
      status: "ACTIVE",
    },
    {
      id: "user-rohit",
      name: "Rohit Mehta",
      email: "rohit.mehta@assetflow.test",
      employeeId: "EMP-0024",
      phone: "+91 98765 11024",
      departmentId: "dept-hr",
      departmentName: "Human Resources",
      role: "MANAGER",
      status: "ACTIVE",
    },
    {
      id: "user-karan",
      name: "Karan Malhotra",
      email: "karan.malhotra@assetflow.test",
      employeeId: "EMP-0031",
      departmentId: "dept-fin",
      departmentName: "Finance",
      role: "MANAGER",
      status: "ACTIVE",
    },
    {
      id: "user-sneha",
      name: "Sneha Iyer",
      email: "sneha.iyer@assetflow.test",
      employeeId: "EMP-0045",
      departmentId: "dept-ops",
      departmentName: "Operations",
      role: "MANAGER",
      status: "ACTIVE",
    },
    {
      id: "user-vikram",
      name: "Vikram Singh",
      email: "vikram.singh@assetflow.test",
      employeeId: "EMP-0053",
      departmentId: "dept-admin",
      departmentName: "Admin",
      role: "ADMIN",
      status: "INACTIVE",
    },
    {
      id: "user-arjun",
      name: "Arjun Nair",
      email: "arjun.nair@assetflow.test",
      employeeId: "EMP-0062",
      departmentId: "dept-rd",
      departmentName: "Research & Development",
      role: "MANAGER",
      status: "ACTIVE",
    },
    {
      id: "user-priya",
      name: "Priya Sharma",
      email: "priya.sharma@assetflow.test",
      employeeId: "EMP-0081",
      phone: "+91 98765 11081",
      departmentId: "dept-it",
      departmentName: "Information Technology",
      role: "EMPLOYEE",
      status: "ACTIVE",
    },
    {
      id: "user-neha",
      name: "Neha Patel",
      email: "neha.patel@assetflow.test",
      employeeId: "EMP-0096",
      departmentId: "dept-ops",
      departmentName: "Operations",
      role: "AUDITOR",
      status: "ON_LEAVE",
    },
  ],
};
