import type { AssetRegistryData } from "./asset.types";

export const dummyAssetRegistryData: AssetRegistryData = {
  user: {
    name: "Asset Manager",
    role: "Asset Manager",
  },

  categories: [
    { id: "cat-electronics", name: "Electronics" },
    { id: "cat-furniture", name: "Furniture" },
    { id: "cat-vehicles", name: "Vehicles" },
    { id: "cat-office", name: "Office Equipment" },
    { id: "cat-networking", name: "Networking Equipment" },
  ],

  departments: [
    { id: "dept-it", name: "Information Technology" },
    { id: "dept-admin", name: "Admin" },
    { id: "dept-fin", name: "Finance" },
    { id: "dept-ops", name: "Operations" },
    { id: "dept-rd", name: "Research & Development" },
  ],

  employees: [
    { id: "emp-priya", name: "Priya Sharma" },
    { id: "emp-rahul", name: "Rahul Verma" },
    { id: "emp-neha", name: "Neha Patel" },
    { id: "emp-mitesh", name: "Mitesh Jain" },
  ],

  assets: [
    {
      id: "asset-1",
      assetTag: "AF-0114",
      name: "Laptop Dell XPS 13",
      serialNumber: "DX13-2025-1008",
      categoryId: "cat-electronics",
      categoryName: "Electronics",
      status: "ASSIGNED",
      condition: "GOOD",
      location: "5th Floor - IT",
      departmentId: "dept-it",
      departmentName: "Information Technology",
      assignedToId: "emp-priya",
      assignedToName: "Priya Sharma",
      acquisitionDate: "2024-05-14",
      acquisitionCost: 124999,
      manufacturer: "Dell",
      model: "XPS 13",
      warrantyExpiry: "2027-05-14",
      isBookable: false,
      notes: "Primary development laptop.",
    },
    {
      id: "asset-2",
      assetTag: "AF-0092",
      name: "iPhone 14",
      serialNumber: "IP14-9082",
      categoryId: "cat-electronics",
      categoryName: "Electronics",
      status: "ASSIGNED",
      condition: "GOOD",
      location: "5th Floor - IT",
      departmentId: "dept-it",
      departmentName: "Information Technology",
      assignedToId: "emp-rahul",
      assignedToName: "Rahul Verma",
      acquisitionDate: "2024-01-10",
      acquisitionCost: 69999,
      manufacturer: "Apple",
      model: "iPhone 14",
      warrantyExpiry: "2026-01-10",
      isBookable: false,
    },
    {
      id: "asset-3",
      assetTag: "AF-0080",
      name: "Meeting Room A",
      serialNumber: "ROOM-A-03",
      categoryId: "cat-furniture",
      categoryName: "Furniture",
      status: "RESERVED",
      condition: "GOOD",
      location: "3rd Floor - Admin",
      departmentId: "dept-admin",
      departmentName: "Admin",
      acquisitionDate: "2023-07-01",
      acquisitionCost: 0,
      isBookable: true,
      notes: "Shared meeting room with 12 seats.",
    },
    {
      id: "asset-4",
      assetTag: "AF-0067",
      name: "Canon EOS 200D",
      serialNumber: "CN-EOS-200D-778",
      categoryId: "cat-electronics",
      categoryName: "Electronics",
      status: "IN_MAINTENANCE",
      condition: "FAIR",
      location: "2nd Floor - Ops",
      departmentId: "dept-ops",
      departmentName: "Operations",
      acquisitionDate: "2022-11-18",
      acquisitionCost: 45500,
      manufacturer: "Canon",
      model: "EOS 200D",
      isBookable: true,
      notes: "Lens focusing issue under repair.",
    },
    {
      id: "asset-5",
      assetTag: "AF-0045",
      name: "Toyota Innova",
      serialNumber: "TS09AB1234",
      categoryId: "cat-vehicles",
      categoryName: "Vehicles",
      status: "AVAILABLE",
      condition: "GOOD",
      location: "Parking - A1",
      departmentId: "dept-admin",
      departmentName: "Admin",
      acquisitionDate: "2021-04-05",
      acquisitionCost: 1950000,
      manufacturer: "Toyota",
      model: "Innova Crysta",
      isBookable: true,
    },
    {
      id: "asset-6",
      assetTag: "AF-0031",
      name: "HP LaserJet Pro",
      serialNumber: "HP-LJP-4401",
      categoryId: "cat-office",
      categoryName: "Office Equipment",
      status: "AVAILABLE",
      condition: "GOOD",
      location: "4th Floor - Finance",
      departmentId: "dept-fin",
      departmentName: "Finance",
      acquisitionDate: "2023-03-22",
      acquisitionCost: 32999,
      manufacturer: "HP",
      model: "LaserJet Pro M404",
      isBookable: false,
    },
    {
      id: "asset-7",
      assetTag: "AF-0026",
      name: "Cisco Network Switch",
      serialNumber: "CS-2960X-4432",
      categoryId: "cat-networking",
      categoryName: "Networking Equipment",
      status: "ACTIVE",
      condition: "GOOD",
      location: "Server Room - IT",
      departmentId: "dept-it",
      departmentName: "Information Technology",
      acquisitionDate: "2022-09-13",
      acquisitionCost: 87000,
      manufacturer: "Cisco",
      model: "Catalyst 2960-X",
      isBookable: false,
    },
    {
      id: "asset-8",
      assetTag: "AF-0019",
      name: "Office Chair",
      serialNumber: "CHR-ERG-101",
      categoryId: "cat-furniture",
      categoryName: "Furniture",
      status: "DECOMMISSIONED",
      condition: "DAMAGED",
      location: "Warehouse",
      departmentId: "dept-admin",
      departmentName: "Admin",
      acquisitionDate: "2019-06-14",
      acquisitionCost: 8500,
      isBookable: false,
      notes: "Retired due to structural damage.",
    },
  ],
};
